spring.application.name=SpringProject
spring.datasource.url=jdbc:mysql://localhost:3306/Demo_project
spring.datasource.username=root
spring.datasource.password=Shubham@7574

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true